import { Inter } from "next/font/google";
import "./globals.css";
import Navmanger from "./GlobalComponents/Navmanger";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Naandi Ventures",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className} style={{color:"white"}}>
        {children}</body>
    </html>
  );
}
